# Market scanning
EVENT_FETCH_LIMIT = 50
MIN_LIQUIDITY = 10_000
MIN_VOLUME_24H = 5_000
MIN_DAYS_TO_RESOLUTION = 14

# Placeholder volatility until real price history is added
DEFAULT_VOLATILITY_5M = 0.02
DEFAULT_VOLATILITY_1H = 0.04

# Risk thresholds
MAX_RESOLUTION_AMBIGUITY = 0.65
MIN_TRADEABILITY = 0.40
MAX_NEWS_RISK_OFF = 0.88
MIN_SPREAD = 0.02
MAX_SPREAD = 0.20
MIN_BID_DEPTH = 100
MIN_ASK_DEPTH = 100
MIN_LIQUIDITY_FOR_TRADING = 10_000
HIGH_NEWS_RISK = 0.70
HIGH_EVENT_SENSITIVITY = 0.70

# Risk score weights
RISK_WEIGHT_NEWS = 0.30
RISK_WEIGHT_EVENT = 0.20
RISK_WEIGHT_AMBIGUITY = 0.20
RISK_WEIGHT_INFORMATION_ASYMMETRY = 0.15
RISK_WEIGHT_MANIPULATION = 0.10
RISK_WEIGHT_VOLATILITY = 0.05

# Quote width settings
BASE_QUOTE_WIDTH = 0.015
VOLATILITY_QUOTE_MULTIPLIER = 2.5
NEWS_RISK_QUOTE_MULTIPLIER = 0.03
AMBIGUITY_QUOTE_MULTIPLIER = 0.02
INFORMATION_ASYMMETRY_QUOTE_MULTIPLIER = 0.015
MAX_QUOTE_WIDTH = 0.12

# Paper trading
PAPER_ORDER_SIZE = 5.0